# Eigen values & Eigen Vectors

4. Using np.linalg.eig, compute the eigenvalues and eigen vectors of A

In [1]:
import numpy as np

# Define a matrix
matrix = np.array([[9, 1, -1], [-1, 11, 1], [-2, 2, 10]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)

Eigenvalues: [12.  8. 10.]
Eigenvectors:
 [[ 9.00258517e-16 -7.07106781e-01 -7.07106781e-01]
 [-7.07106781e-01 -3.36518470e-16 -7.07106781e-01]
 [-7.07106781e-01 -7.07106781e-01 -5.62025848e-15]]
